All: true
transaction_pool_input_throughput: true
db_state_write_rate: true 
db_state_read_rate: true
tx_queue_delay: true
block_commit_duration_start: true
block_commit_duration_end: true
block_validation_efficiency_start: true
block_validation_efficiency_end: true
tx_delay_start: true 
tx_delay_end: true
tx_in_block_tps: true
contract_time: true
Cpumem: true
net_p2p_transmission_latency: true
peer_message_throughput: true
consensus_clique_cost: true



contract_execute_efficiency: false
block_tx_conflict_rate: false
consensus_tbft_cost: false
block_validation_efficiency: false
block_commit_duration: false