---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-test-node1
  labels:
    buaa-gitlab-ci: 'ethereum-test'
spec:
  selector:
    matchLabels:
      app: ethereum-test-node1
  template:
    metadata:
      labels:
        app: ethereum-test-node1
    spec:
      nodeName: 192.168.0.41
      containers:
      - name: node
        image: swr.cn-north-4.myhuaweicloud.com/buaa-dist-compute-ci/ethereum-recorder:4_9
        workingDir: '/usr/local/bin'
        command:
          - '/bin/sh'
          - '-c'      
          - './start_node1.sh && tail -f /dev/null'
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 30303
        - containerPort: 8545
        - containerPort: 8546
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-test-instance1
  labels:
    buaa-gitlab-ci: 'ethereum-test'
spec:
  type: NodePort
  selector:
    app: ethereum-test-node1
  ports:
  - name: p2p
    nodePort: 30303
    port: 30303
    targetPort: 30303
